// ignore_for_file: avoid_print
//
// Generates the selector capability matrix in README.md from the code itself.
//
// The old README carried a hand-written "Limitations" paragraph that drifted
// from reality — it listed selectors as unsupported that were, and omitted
// ones that were broken. This derives the table from MatchSupport, so the
// documentation cannot disagree with the implementation.
//
// Usage:
//   dart run tool/generate_capability_matrix.dart          # rewrite README
//   dart run tool/generate_capability_matrix.dart --check   # CI: verify only
import 'dart:io';

import 'package:cascadia/cascadia.dart';

const startMarker = '<!-- BEGIN GENERATED CAPABILITY MATRIX -->';
const endMarker = '<!-- END GENERATED CAPABILITY MATRIX -->';

/// Every selector the library claims to support, grouped for presentation.
const Map<String, List<String>> groups = <String, List<String>>{
  'Basic': [
    '*',
    'div',
    '.cls',
    '#id',
    '[attr]',
    '[attr="v"]',
    '[attr~="v"]',
    '[attr|="v"]',
    r'[attr^="v"]',
    r'[attr$="v"]',
    '[attr*="v"]',
    'svg|rect'
  ],
  'Combinators': ['div p', 'div > p', 'h1 + p', 'h1 ~ p', 'h1, h2'],
  'Tree-structural': [
    ':root',
    ':empty',
    ':first-child',
    ':last-child',
    ':only-child',
    ':nth-child(2n+1)',
    ':nth-last-child(2)',
    ':first-of-type',
    ':last-of-type',
    ':only-of-type',
    ':nth-of-type(2)',
    ':nth-last-of-type(2)'
  ],
  'Logical': [':not(.a)', ':is(h1, h2)', ':where(.a)', ':has(p)', ':has(> p)'],
  'Forms': [
    ':enabled',
    ':disabled',
    ':checked',
    ':default',
    ':required',
    ':optional',
    ':read-only',
    ':read-write',
    ':placeholder-shown',
    ':indeterminate',
    ':valid',
    ':invalid',
    ':in-range',
    ':out-of-range',
    ':user-valid',
    ':user-invalid',
    ':blank',
    ':autofill'
  ],
  'Links & location': [
    ':any-link',
    ':link',
    ':visited',
    ':local-link',
    ':target',
    ':target-within',
    ':scope'
  ],
  'Interaction': [
    ':hover',
    ':active',
    ':focus',
    ':focus-visible',
    ':focus-within'
  ],
  'Display state': [
    ':open',
    ':modal',
    ':fullscreen',
    ':popover-open',
    ':defined',
    ':state(x)',
    ':picture-in-picture'
  ],
  'Linguistic': [':lang(en)', ':dir(ltr)'],
  'Media': [
    ':muted',
    ':paused',
    ':playing',
    ':buffering',
    ':seeking',
    ':stalled',
    ':volume-locked'
  ],
  'Shadow DOM': [':host', ':host(.a)', ':host-context(.a)', ':has-slotted'],
  'Non-standard': [
    ':contains("x")',
    ':containsown("x")',
    ':matches(/x/)',
    ':matchesown(/x/)',
    ':haschild(p)',
    ':heading',
    ':heading(2n)',
    ':input'
  ],
  'Pseudo-elements': [
    '::before',
    '::after',
    '::first-line',
    '::first-letter',
    '::marker',
    '::placeholder',
    '::selection',
    '::backdrop',
    '::part(x)',
    '::slotted(p)',
    '::highlight(x)',
    '::view-transition'
  ],
};

/// Escapes a selector for use inside a markdown table cell.
///
/// A literal `|` (as in `svg|rect` or `[attr|="v"]`) would otherwise be read
/// as a column separator and break the table.
String cell(String css) => '`${css.replaceAll('|', r'\|')}`';

String describe(String css) {
  final Sel sel;
  try {
    sel = css.contains('::') ? parseWithPseudoElements(css) : parse(css);
  } on FormatException {
    return '| ${cell(css)} | ❌ not supported | rejected at parse time |';
  }
  final needs = sel.undecidableParts.map((n) => n.replaceAll('|', r'\|'));
  return switch (sel.support) {
    MatchSupport.decidable =>
      '| ${cell(css)} | ✅ full | matches against the DOM |',
    MatchSupport.requiresContext =>
      '| ${cell(css)} | ⚙️ needs context | supply ${needs.join(", ")} via `MatchContext` |',
    MatchSupport.neverDecidable =>
      '| ${cell(css)} | ⬜ parse only | represents a rendered fragment; never matches a node |',
  };
}

String buildMatrix() {
  final out = StringBuffer()
    ..writeln(startMarker)
    ..writeln()
    ..writeln('<!-- Generated by tool/generate_capability_matrix.dart.')
    ..writeln('     Do not edit by hand; run the tool to refresh. -->')
    ..writeln()
    ..writeln('| Support | Meaning |')
    ..writeln('| --- | --- |')
    ..writeln('| ✅ full | Decided from the DOM alone. |')
    ..writeln('| ⚙️ needs context | Correct once you pass the required '
        'runtime state in a `MatchContext`; without it, treated as a '
        'non-match (or throws under `strict: true`). |')
    ..writeln('| ⬜ parse only | Parses and serializes, but denotes a '
        'rendered fragment rather than an element, so it never matches. |')
    ..writeln();

  var full = 0;
  var ctx = 0;
  var parseOnly = 0;
  for (final entry in groups.entries) {
    out
      ..writeln('#### ${entry.key}')
      ..writeln()
      ..writeln('| Selector | Support | Notes |')
      ..writeln('| --- | --- | --- |');
    for (final css in entry.value) {
      final row = describe(css);
      if (row.contains('✅')) {
        full++;
      } else if (row.contains('⚙️')) {
        ctx++;
      } else {
        parseOnly++;
      }
      out.writeln(row);
    }
    out.writeln();
  }
  out
    ..writeln('**Totals:** $full fully supported · $ctx context-dependent · '
        '$parseOnly parse-only.')
    ..writeln()
    ..writeln(endMarker);
  return out.toString().trimRight();
}

void main(List<String> args) {
  final check = args.contains('--check');
  final readme = File('README.md');
  if (!readme.existsSync()) {
    stderr.writeln('README.md not found; run from the package root.');
    exit(2);
  }

  final content = readme.readAsStringSync();
  final start = content.indexOf(startMarker);
  final end = content.indexOf(endMarker);
  if (start < 0 || end < 0) {
    stderr.writeln('Markers not found in README.md. Add:\n'
        '$startMarker\n$endMarker');
    exit(2);
  }

  final updated =
      content.replaceRange(start, end + endMarker.length, buildMatrix());

  if (check) {
    if (updated != content) {
      stderr.writeln('README.md capability matrix is stale. '
          'Run: dart run tool/generate_capability_matrix.dart');
      exit(1);
    }
    print('Capability matrix is up to date.');
    return;
  }

  readme.writeAsStringSync(updated);
  print('Updated the capability matrix in README.md.');
}
